### ISSUE TITLE
CoGAN

### ISSUE THREAD

**Issue by mmosquera10** [kozistr/Awesome-GANs#6]
Hello,

I am trying to run CoGAN, but I get the following error below:

Traceback (most recent call last):
  File "cogan_train.py", line 131, in <module>
    main()
  File "cogan_train.py", line 42, in main
    model = cogan.CoGAN(s)
  File "/home/maria/Documents/Awesome-GANs/CoGAN/cogan_model.py", line 166, in __init__
    self.build_cogan()  # build CoGAN model
  File "/home/maria/Documents/Awesome-GANs/CoGAN/cogan_model.py", line 224, in build_cogan
    self.g_1 = self.generator(self.z, self.y, share_params=False, reuse=False, name='g1')
  File "/home/maria/Documents/Awesome-GANs/CoGAN/cogan_model.py", line 196, in generator
    x = tf.layers.dense(x, 7 * 7, reuse=True, name='gen-dense-reshape')
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 250, in dense
    return layer.apply(inputs)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 671, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 559, in __call__
    self.build(input_shapes[0])
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 137, in build
    trainable=True)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 458, in add_variable
    trainable=trainable and self.trainable)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1203, in get_variable
    constraint=constraint)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1092, in get_variable
    constraint=constraint)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/maria/anaconda2/envs/anaconda3gpu/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 760, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable generator-g1/gen-dense-reshape/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

Any help would be greatly appreciated! Thank you in advance.

**Comment by kozistr** [comment]
Currently, CoGAN is under development! Almost done, but it'll not work properly, in now :(
I'll fix CoGAN ASAP! (I'll leave a comment when i'm done finishing CoGAN :))

Also, you can check available GAN models in ```Papers & Codes``` Section in README.md!

Thank you :)

**Comment by kozistr** [comment]
CoGAN fixed! Now, it works well :) (now running on my machine).

After running it, I'll upload results on CoGAN page.

**Comment by mmosquera10** [comment]
Thank you for fixing the issue. I was able to run it, but the image generation is not good. It seems nothing is getting generated. It's on the 75,000 step. I left it training for more steps to see if it improves the image quality. Are you facing the same issue?

**Comment by kozistr** [comment]
Yes, me too, facing same issue :(.  But i just found the problems!

Now, i'm on fixing the bugs, So it'll be updated soon!.
This time, I'll notice you by comment after checking the whole CoGAN results :).

Thanks again :)

**Comment by kozistr** [comment]
I'll close this issue :). If there're any questions, please re-open an issue!

Thank you
